#!/usr/bin/env bash

parallel-ssh -h hosts 'mkdir -p /home/cyrill/go/src/github.com/scionproto/scion/'
parallel-rsync -h hosts -r -x "--exclude .git" -x "--exclude .bazel-cache" -x "-L" -x "--include bazel-bin/go/flowtele/***" -x"--include bazel-bin/go/examples/pingpong/***" -x "--include */" -x "--exclude bazel-bin/***" -x "--exclude bazel-out/***" -x "--exclude bazel-scion/***" -x "--prune-empty-dirs" /home/cyrill/go/src/github.com/scionproto/scion /home/cyrill/go/src/github.com/scionproto/
